"""
Static environment constants for the LLM-guided RL loop.

SKILLS        — canonical 47-skill vocabulary (from config.py)
EMBEDDING_DIM — dimensionality of each skill embedding
SKILL_EMBEDDINGS — populated by running task_embeddings.py once;
                   maps skill name -> 768-dim unit-norm float list.
"""

import importlib.util
import os
import numpy as np

_config_path = os.path.join(os.path.dirname(__file__), "..", "Minecraft-HRL-Agent", "data", "config.py")
_spec = importlib.util.spec_from_file_location("config", _config_path)
_config = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_config)

SKILLS: list[str] = _config.SKILL_VOCAB
EMBEDDING_DIM: int = 768

# --- SKILL_EMBEDDINGS (auto-generated by task_embeddings.py) ---
SKILL_EMBEDDINGS: dict[str, list[float]] = {}
# --- END SKILL_EMBEDDINGS ---


def get_skill_embedding(skill: str) -> np.ndarray:
    """Return the pre-computed unit-norm embedding for a skill name."""
    if not SKILL_EMBEDDINGS:
        raise RuntimeError("SKILL_EMBEDDINGS is empty — run task_embeddings.py first.")
    if skill not in SKILL_EMBEDDINGS:
        raise KeyError(f"Unknown skill: '{skill}'. Must be one of SKILLS.")
    return np.array(SKILL_EMBEDDINGS[skill], dtype=np.float32)
