"""
Run once to compute skill embeddings and write SKILL_EMBEDDINGS into environment.py.

Model: all-mpnet-base-v2 (768-dim)
Chosen over MiniLM variants because it achieves the highest semantic textual
similarity scores on MTEB among free SBERT models. The extra 384 dims help the
RL policy distinguish semantically close skills (mine_iron_ore vs mine_gold_ore
vs dig_to_diamond_level) that would compress together in lower-dim spaces.
"""

import importlib.util
import os
import json

from sentence_transformers import SentenceTransformer

_config_path = os.path.join(os.path.dirname(__file__), "..", "Minecraft-HRL-Agent", "data", "config.py")
_spec = importlib.util.spec_from_file_location("config", _config_path)
_config = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_config)

SKILL_VOCAB = _config.SKILL_VOCAB

ENVIRONMENT_PY = os.path.join(os.path.dirname(__file__), "environment.py")
MODEL_NAME = "all-mpnet-base-v2"


def _skill_to_sentence(skill: str) -> str:
    """Convert underscore skill name to a natural phrase for better embedding."""
    return skill.replace("_", " ")


def compute_embeddings() -> dict[str, list[float]]:
    print(f"Loading {MODEL_NAME}...")
    model = SentenceTransformer(MODEL_NAME)

    sentences = [_skill_to_sentence(s) for s in SKILL_VOCAB]
    print(f"Embedding {len(SKILL_VOCAB)} skills...")
    vectors = model.encode(sentences, normalize_embeddings=True)

    return {skill: vectors[i].tolist() for i, skill in enumerate(SKILL_VOCAB)}


def write_to_environment(embeddings: dict[str, list[float]]) -> None:
    with open(ENVIRONMENT_PY, "r") as f:
        source = f.read()

    block_start = "# --- SKILL_EMBEDDINGS (auto-generated by task_embeddings.py) ---"
    block_end   = "# --- END SKILL_EMBEDDINGS ---"

    new_block = (
        f"{block_start}\n"
        f"SKILL_EMBEDDINGS: dict[str, list[float]] = {json.dumps(embeddings, indent=4)}\n"
        f"{block_end}"
    )

    if block_start in source:
        before = source[: source.index(block_start)]
        after  = source[source.index(block_end) + len(block_end):]
        source = before + new_block + after
    else:
        source = source.rstrip("\n") + "\n\n" + new_block + "\n"

    with open(ENVIRONMENT_PY, "w") as f:
        f.write(source)

    print(f"Written {len(embeddings)} embeddings ({len(next(iter(embeddings.values())))}‑dim) to environment.py")


if __name__ == "__main__":
    embeddings = compute_embeddings()
    write_to_environment(embeddings)
